In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame
from sklearn import linear_model
import matplotlib as plt
num={"Age":[25,30,35,40,45],"Height":[162.56,172.72,167.64,np.nan,157.48],
     "Weight":[70,95,78,110,85],"Premium":[18000,38000,38000,60000,70000]}
df=pd.DataFrame(num)
df

Age  Height  Weight  Premium
0   25  162.56      70    18000
1   30  172.72      95    38000
2   35  167.64      78    38000
3   40     NaN     110    60000
4   45  157.48      85    70000

In [5]:
mean_height=df.Height.mean()
mean_height


165.1

In [8]:
df.Height=df.Height.fillna(mean_height)
df

Age  Height  Weight  Premium
0   25  162.56      70    18000
1   30  172.72      95    38000
2   35  167.64      78    38000
3   40  165.10     110    60000
4   45  157.48      85    70000

In [9]:
model=linear_model.LinearRegression()
model.fit(df[['Age','Height','Weight']],df[['Premium']])


LinearRegression()

In [10]:
model.predict([[26,170,65]])

array([[17164.25257237]])

In [11]:
model.coef_

array([[2150.26052416, -248.45851574,  312.65291961]])

In [12]:
model.intercept_

array([-16827.01315482])

In [13]:
2150.26052416*26+-248.45851574*170+312.65291961*65+-16827.01315482

17164.252572190002