In [1]:
import numpy

In [3]:
np=numpy.array([1,2,3,4,8,6,9])
np

array([1, 2, 3, 4, 8, 6, 9])

In [7]:
np=numpy.arange(20,50)
np

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [8]:
import numpy
a=numpy.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
b=numpy.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
b.reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [13]:
b=slice(3,10,2)
a[b]

array([3, 5, 7, 9])

In [3]:
import numpy as np
a=np.arange(0,130,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])