In [1]:
print("hello")

hello


In [2]:
import numpy as np


In [3]:
print(np)
np

<module 'numpy' from 'E:\\Anaconda\\lib\\site-packages\\numpy\\__init__.py'>


<module 'numpy' from 'E:\\Anaconda\\lib\\site-packages\\numpy\\__init__.py'>

In [4]:

import numpy as np
temp=[21.2,22.5,25.7,26.4]
c=np.array(temp)
print(c)

[21.2 22.5 25.7 26.4]


In [5]:
print(c*9/5+32)

[70.16 72.5  78.26 79.52]


In [6]:
print(c)

[21.2 22.5 25.7 26.4]


In [7]:
f_temp=[x*9/5+32 for x in temp]
print(f_temp)

[70.16, 72.5, 78.25999999999999, 79.52]


In [8]:
fah=[c*9/5+32]
print(fah)

[array([70.16, 72.5 , 78.26, 79.52])]


In [9]:
type(fah)

list

In [10]:
##############  Read excel file
import pandas 

In [11]:
df=pandas.read_excel("Sample.xls")
df

0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [12]:
df

0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [13]:
import numpy as np

In [14]:
a=np.logspace(2.0,3.0)

In [15]:
a

array([ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
        120.67926406,  126.48552169,  132.57113656,  138.94954944,
        145.63484775,  152.64179672,  159.98587196,  167.68329368,
        175.75106249,  184.20699693,  193.06977289,  202.35896477,
        212.09508879,  222.29964825,  232.99518105,  244.20530945,
        255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
        308.88435965,  323.74575428,  339.32217719,  355.64803062,
        372.75937203,  390.69399371,  409.49150624,  429.19342601,
        449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
        542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
        655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
        790.60432109,  828.64277285,  868.51137375,  910.29817799,
        954.09547635, 1000.        ])

In [16]:
import pandas
from pandas import DataFrame
from pandas import Series
df=pandas.read_excel("Sample.xls")
df

0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [17]:
d=DataFrame(df)

In [18]:
d

0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [19]:
d.sort_values("Age")

0 First Name  Last Name  Gender        Country  Age        Date    Id
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468

In [20]:
d.sort_index()

0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [21]:
 d.sort_values("Date")

0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [22]:
df

0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [23]:
d

0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [24]:
d.sum()

0                                                            45
First Name    DulceMaraPhilipKathleenNereidaGastonEttaEarlea...
Last Name     AbrilHashimotoGentHannerMagwoodBrummHurnMelgar...
Gender        FemaleFemaleMaleFemaleFemaleMaleFemaleFemaleFe...
Country       United StatesGreat BritainFranceUnited StatesU...
Age                                                         323
Date          15/10/201716/08/201621/05/201515/10/201716/08/...
Id                                                        26904
dtype: object

In [25]:
import pandas
from pandas import DataFrame
from pandas import Series
df=pandas.read_excel("Sample.xls")
df

0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [26]:
df.T

0              1           2              3  \
0                       1              2           3              4   
First Name          Dulce           Mara      Philip       Kathleen   
Last Name           Abril      Hashimoto        Gent         Hanner   
Gender             Female         Female        Male         Female   
Country     United States  Great Britain      France  United States   
Age                    32             25          36             25   
Date           15/10/2017     16/08/2016  21/05/2015     15/10/2017   
Id                   1562           1582        2587           3549   

                        4              5              6              7  \
0                       5              6              7              8   
First Name        Nereida         Gaston           Etta        Earlean   
Last Name         Magwood          Brumm           Hurn         Melgar   
Gender             Female           Male         Female         Female   
Country     United States  United States  Great Britain  United States   
Age                    58             24             56             27   
Date           16/08/2016     21/05/2015     15/10/2017     16/08/2016   
Id                   2468           2554           3598           2456   

                        8  
0                       9  
First Name       Vincenza  
Last Name         Weiland  
Gender             Female  
Country     United States  
Age                    40  
Date           21/05/2015  
Id                   6548

In [27]:
df

0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [28]:
a=df["First Name"]

In [29]:
a

0       Dulce
1        Mara
2      Philip
3    Kathleen
4     Nereida
5      Gaston
6        Etta
7     Earlean
8    Vincenza
Name: First Name, dtype: object

In [30]:
df

0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [31]:
b=df.pop("Age")
b

0    32
1    25
2    36
3    25
4    58
5    24
6    56
7    27
8    40
Name: Age, dtype: int64